/**
 * Product Data Model
 * Represents a fashion item in the catalog
 */
export interface Product {
  sku_id: string;
  title: string;
  sector: string;
  lowest_price: number;
  brand_name: string;
  category: string;
  sub_category: string;
  product_type: string;
  gender: string;
  description: string;
  tags: string[];
  featured_image: string;
  
  // Derived attributes for recommendation engine
  color_family?: ColorFamily;
  style?: StyleType;
  season?: Season;
}

export type ColorFamily = 
  | 'black' 
  | 'white' 
  | 'gray' 
  | 'navy' 
  | 'brown' 
  | 'beige' 
  | 'cream'
  | 'green'
  | 'blue'
  | 'red'
  | 'pink'
  | 'purple'
  | 'orange'
  | 'multi';

export type StyleType = 
  | 'streetwear' 
  | 'casual' 
  | 'athletic' 
  | 'formal' 
  | 'luxury'
  | 'minimalist';

export type Season = 
  | 'all' 
  | 'summer' 
  | 'winter' 
  | 'spring' 
  | 'fall';

export type ProductCategory = 
  | 'tops'
  | 'bottoms'
  | 'footwear'
  | 'accessories';

/**
 * Outfit Combination
 * A complete look generated by the recommendation engine
 */
export interface Outfit {
  id: string;
  top: Product;
  bottom: Product;
  footwear: Product;
  accessories: Product[];
  match_score: number; // Style match score for user display (0-1)
  score_breakdown: ScoreBreakdown;
  reasoning: string;
  total_price: number;
}

/**
 * Score Breakdown
 * Explains how the match score was calculated
 */
export interface ScoreBreakdown {
  color_harmony: number;      // 0-1: How well colors complement each other
  style_match: number;        // 0-1: Style consistency across items
  brand_cohesion: number;     // 0-1: Brand tier compatibility
  price_balance: number;      // 0-1: Price range consistency
  season_fit: number;         // 0-1: Seasonal appropriateness
}

/**
 * Recommendation Request
 */
export interface RecommendationRequest {
  base_product_id: string;
  preferred_style?: StyleType;
  season?: Season;
  num_outfits?: number;
}

/**
 * Recommendation Response
 */
export interface RecommendationResponse {
  outfits: Outfit[];
  base_product: Product;
  processing_time_ms: number;
  cache_hit: boolean;
}
